### PR TITLE
Unit tests for API endpoints

### LINKED ISSUE #30: Create unit tests for current endpoints
Considering streamline the current testing process, create unit tests for endpoints without touching database

### PR DESCRIPTION
**Pull request by yeshengliu**
# Description

Add unit tests for API endpoints

Closes #30

## Type of change

- New feature (non-breaking change which adds functionality)

```bash
> npm test
```

### CODE REVIEW

**Comment by yeshengliu** [comment]
I referred to [https://www.prisma.io/blog/testing-series-1-8eRB5p0Y8o](url)

For some reason the test passed after I was trying to create a record in Brain collection, but this is not expected. The response from endpoint is returning the record that I just created. Not sure if prisma.*.create.mockResolvedValue()` is the correct method to call.

**Comment by hdavidethan** [comment]
Ok so I looked at both the code and the docs and I can probably clear up some confusion:

The use of `mockResolvedValues()` is not quite in the right place. So the idea here is that rather than create a memory DB, we are simply pretending as if Prisma will return this value after the function is called. So in the case of using the method on `prisma.user.create.mockResolvedValues()`, this just means that the next time `prisma.user.create()` is called, the value returned will match what you used in the mock, _but not actually persist throughout prisma_.

A bit of a side note, your observation that when you removed the brains mock that it stopped working is also related to the behavior of mocking prisma. In the entire test environment, prisma is not connected at all, so any invocation to queries or mutations will only produce `undefined` values.

Back to the purpose of `mockResolvedValues()`, this method is used to replace the otherwise `undefined` values with an expected value. The assumption is that Prisma operates in a deterministic manner and has been tested separately.

How does this bring us back to unit tests? So, the purpose of writing the test is to exercise various behaviors in correct and incorrect API usages. If you are testing the POST /brains endpoint, you should be testing the various ways a person could incorrectly encode the parameters. Since we have already assumed that Prisma is working 100% correctly, the prescribed way would be to use `mockResolvedValues()` to provide what Prisma would have provided given that it was working.

Of course, this is not always the ideal case. A more realistic testing environment would involve spinning up an actual DB, but given the time constraints, I would advise against this for now.

**Comment by hdavidethan** [comment]
I think that for now we can set this aside first and revisit later once we have finished other higher priority tasks.

**Comment by yeshengliu** [comment]
@hdavidethan Thank you David! This really clarifies my confusion that why the response always returns `undefined` after calling `prisma.brain.create` is simply because prisma is not connected during the test. I think unit tests for the endpoints that we have implemented so far are kinda awkward here because most actions are against the database.

**Comment by hdavidethan** [comment]
Yes indeed. I think this also brings up the next topic which is: are API endpoints really necessary in this use case. So, we're already using Next.js, which is server-side. It would actually be better to simply call library functions directly in the context of server components. What are your thoughts on this?

**Comment by yeshengliu** [comment]
ok... this brings us back to my day one when I sent you a link about trpc. REST is indeed kinda verbose given our use cases do not involve too much complicated logics. I think the main benefit of REST is scalability say like we have multiple apps in future that can share a single back-end but I think a web app is already sufficient for most use cases nowadays. But REST is definitely a well-proven solution so I don't know if new technologies like trpc can create more hassle in dealing with complex queries

**Pull request closed without merging**
